# prakashecho/docker/.github/workflows/dependency.yaml

name: Dependency Installation

on:
  workflow_call:
    inputs:
      install-all:
        description: 'Toggle installation of all dependencies'
        required: false
        default: 'false'
        type: 'string'
      install-curl:
        description: 'Toggle installation of curl'
        required: false
        default: 'false'
        type: 'string'
      install-git:
        description: 'Toggle installation of git'
        required: false
        default: 'false'
        type: 'string'
      install-gh:
        description: 'Toggle installation of GitHub CLI'
        required: false
        default: 'false'

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Install curl
        if: ${{ inputs.install-all == 'true' || inputs.install-curl == 'true' }}
        run: sudo apt-get install -y curl

      - name: Install git
        if: ${{ inputs.install-all == 'true' || inputs.install-git == 'true' }}
        run: sudo apt-get install -y git

      - name: Install GitHub CLI
        if: ${{ inputs.install-all == 'true' || inputs.install-gh == 'true' }}
        run: |
          sudo apt-get install -y gh
          gh version
