
on:
  workflow_call:
    inputs:
      releaseVersion:
        type: string
        description: Version of the image to push
        required: true

permissions:
  contents: read
  packages: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ inputs.releaseVersion }}-${{ matrix.platform == 'linux/amd64' && 'amd64' || 'arm64' }}

      - name: Export digest
        run: |
          platform_suffix="${{ matrix.platform == 'linux/amd64' && 'amd64' || 'arm64' }}"
          echo "${{ steps.docker_build.outputs.digest }}" > /tmp/digest-${{ matrix.platform }}

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digest-${{ matrix.platform }}
          path: /tmp/digest-${{ matrix.platform }}
          if-no-files-found: error

  merge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests

      - name: Create manifest list and push
        run: |
          set -x
          
          # List the contents of the digests directory
          ls -la /tmp/digests
          
          # Read digests and create manifest
          manifest_args=""
          for platform in "linux/amd64" "linux/arm64"; do
            digest=$(cat /tmp/digests/digest-${platform}/digest-${platform})
            manifest_args="$manifest_args ghcr.io/${{ github.repository }}@${digest}"
          done
          
          # Create and push the manifest list
          docker buildx imagetools create \
            -t ghcr.io/${{ github.repository }}:latest \
            -t ghcr.io/${{ github.repository }}:${{ inputs.releaseVersion }} \
            $manifest_args

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ghcr.io/${{ github.repository }}:${{ inputs.releaseVersion }}
